spring:
  application:
    name: test
  r2dbc:
#    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/assignment?serverTimezone=+07:00}
    url: r2dbc:mysql://localhost:3306/assignment?serverTimezone=+07:00
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:123456}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m



